// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdN37FRxxdLx1BR9wRkF5BLy9Tru3Fwho',
    appId: '1:410231518567:android:e2d91369775f3d0aff2bc2',
    messagingSenderId: '410231518567',
    projectId: 'react-native-project-2a571',
    storageBucket: 'react-native-project-2a571.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmjFXlnA0ULs-Lj67UAAKZjzNvf36cD2M',
    appId: '1:410231518567:ios:76b46a2df41f907fff2bc2',
    messagingSenderId: '410231518567',
    projectId: 'react-native-project-2a571',
    storageBucket: 'react-native-project-2a571.appspot.com',
    iosClientId: '410231518567-mgpo1fc4pofmeqhf83vsun3gb0fdenf3.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetAirways',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAYIbN2gziA861UOR8YFqc2O2eeYTtpxXE",
      authDomain: "react-native-project-2a571.firebaseapp.com",
      projectId: "react-native-project-2a571",
      storageBucket: "react-native-project-2a571.appspot.com",
      messagingSenderId: "410231518567",
      appId: "1:410231518567:web:1e8b7936bba9aadcff2bc2",
      measurementId: "G-HKE2RT8QLY"
  );

}
